#!/usr/bin/env ruby

require 'aws-sdk'

class AwsInstanceManager
  def list_instances()
    ec2 = Aws::EC2::Client.new(region: 'us-west-2');
    resp = ec2.describe_instances()
    resp.reservations.each do |res|
      res.instances.each do |inst|
        puts inst
        iid = inst[:instance_id]
        istate = inst[:state].name
        ipublicdns = inst[:public_dns_name]
        ipublicip = inst[:public_ip_address]
        puts "#{iid} #{istate} #{ipublicdns} #{ipublicip}"
      end
    end
  end
end

if __FILE__ ==$0
  aws = AwsInstanceManager.new
  aws.list_instances();
end
